spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:15432/user_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

spring.cache.type=caffeine
spring.cache.cache-names=exchangeRates
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=24h

eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8761/eureka/

keycloak.server-url=http://localhost:9090
keycloak.realm=financemate-realm
keycloak.client-id=auth-service-backend
keycloak.client-secret=kJPiAacb0feWsWTKqmwdoVdPUAAWGmId

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=adminpassword